name: '247-cfe-compatible'
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pandas<2.0
  - pypsa=0.26.*
  - yaml
  - ca-certificates
  - certifi
  - openssl
  - pypdf2=1.28.4
  - pip
  - linopy=0.3.*
  - geopandas
  - seaborn
  - oyaml
  - snakemake
  - ipykernel
  - highs
  - xarray<2024.12
  - pip:
    - vresutils
    - highspy
